# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: 'git clone https://github.com/hammondjm/ksa.git'

- task: Npm@1
  inputs:
    command: 'install'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-DskipTests=true'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
  displayName: 'Download the latest Unified Agent'
 
- script: 'java -jar wss-unified-agent.jar -product KSA -project KSA-EUA -appPath ./ksa-web-core/target/ksa-web-core-3.9.2.jar -d ./ksa-web-core'
  displayName: 'Run Unified Agent Scan'